[package]
name = "util"
version = "0.1.0"
authors = ["Sander <sander@shageman.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1.5.2"
paste = "1.0"
colored = "2.0"
